### ISSUE TITLE
[Question] zsh compatibility

### ISSUE THREAD

**Issue by Emmanuel-Italic** [krkn/sote#7]
I'd like to use *sote* but i'm using zsh.

It's just a reminder for when you'll have some time. ;)

**Comment by leny** [comment]
Hi, I'm a bit busy right now, and not sure how to add all the things to make sote compatible with bash and zsh, but you can find a zsh-fixed version of sote [here](https://github.com/leny/pwendok/tree/master/zsh/custom/plugins/sote).
